### ISSUE TITLE
Raise the Page Weight Ceiling

### ISSUE THREAD

**Issue by mhartz** [tmpworldwide/tmpworldwide.github.io#16] opened 2015-04-16 17:49 UTC
Right now the Performance budget says that the Cumulative page weight should be around 450-550 KB. However after backend loads, adding something as small as a custom font alone can push a site over the limit. Add the fact that banner images are getting larger, social feeds are brought in, etc. it is near impossible to make a page weight under 600 KB.

Curious to see what others think about this issue.

**Comment by sbkates** [comment] 2015-04-16 18:00
I agree that the page weight suggestion is very idealistic considering the lack of creative decisions we are allowed to make. Every site I make seems to have some custom piece of tracking script, or video implementation, or many custom fonts, or a variety of enormous banner images. I've even had some humongous background images recently that couldn't be reproduced with pure CSS. If I had any sort of creative power, I would have pushed back on that - but I received the PSD's after they had already been reviewed and approved. 

I think that the page weight we land on should be seen more as a suggestion than a requirement, if we have good reason to go over it (and I have on all of my recent projects here.)

**Comment by michaelspellacy** [comment] 2015-04-20 19:42
I think it is high enough as it is given that the average size of a page should be much lower than this (like a couple hundred KB). I wouldn't look at it as an absolute number to hit, but more of a range and something to certainly strive for. If you do happen to be a couple of hundred KB over, it is not the end of the world as long as you attempted to do everything in your power to get it as low as possible. Again, it's a challenge to developers and not an absolute rule. 

Rather than raise ceiling, let's raise awareness for some of the things we can be doing to optimize better. How about a checklist? We love those! With fonts, for instance, how often do we pull out embedded subsets of a font that may not be in use on a site? This would lighten the load considerably. We might also recommend not loading web fonts on mobile under some conditions.  Social can also be loaded on demand instead of behind the scenes on page load.

**Comment by michaelspellacy** [comment] 2015-04-20 19:49
@sylviakates Are you optimizing your banners? As for video, perhaps self-hosting them would make more sense. HTML5 video is a beautiful thing. I dig YouTube, but it can be a heavy load. Sometimes I get sneaky and drop an image in and then link off to video on YouTube or pull it in dynamically to avoid the extra KB. >;-)

**Comment by michaelspellacy** [comment] 2015-04-20 19:58
Check this out. Nice. https://developers.google.com/fonts/docs/getting_started#Subsets

**Comment by michaelspellacy** [comment] 2015-04-20 21:19
Also going to look into what we can do to reduce code weight coming in from back-end. tb-core.js is pretty big (but that is because it loads in jQuery as well - maybe ~70kb is that).

**Comment by michaelspellacy** [comment] 2015-04-20 21:32
Also, I never thought it was very fair for just developers to adhere to a performance budget, but at the time, I thought at least one group should be mindful of it and what better group than all of you fine people? I think it has worked to some degree and I am glad for it, but in order to be _truly_ successful, I believe that executing one properly requires team involvement. This means that a designer should also be aware of what we are striving for here so that they can make more informed decisions. Digital strategist should also be aware of it before promising a shiny social widget. Performance is really a team effort. Until everybody is on the same page, it will only ever be a middle-of-the-road budget. :-(

cc: @JakeRuef

**Comment by michaelspellacy** [comment] 2015-05-08 16:01
Can we close this one out, guys?

**Comment by michaelspellacy** [comment] 2015-05-08 16:21
I think it might be good idea to amend the content:

As part of our commitment to provide users with the best experience possible, we adhere to a performance budget for sites that we develop. Each front-end developer should monitor site performance during development, and each site goes through a performance audit during the QA process.

**While each site is different, we set a single goal here to remind us of the importance of performance and strive to meet those numbers as best as we possibly can.**

**Comment by mhartz** [comment] 2015-05-28 20:29
I agree with what you have added in. But I was thinking maybe a short checklist like you mentioned would be beneficial for code reviewing other than generically asking, "Did the developer do everything in their power to have the lightest page load?"

Thoughts?

**Closed as completed** 2016-06-28 19:31 UTC
